---
- hosts: all
  user: vagrant
  gather_facts: no
  tasks:
    - command: "uname -a"

- hosts: host
  become: yes
  user: vagrant
  gather_facts: no
  tasks:
    - name: write server interfaces configuration
      copy: src=config_{{inventory_hostname}} dest=/etc/network/interfaces.d/interfaces_config
    - name: reload networking
      command: ifreload -a      
